In [1]:
#Numpy

In [2]:
import numpy as np

In [3]:
array_one = np.array([1,2,3,4,5])
array_one

array([1, 2, 3, 4, 5])

In [5]:
type(array_one)

numpy.ndarray

In [6]:
numbers = [9,8,7,6]

In [7]:
array_two = np.array(numbers)

In [8]:
array_two

array([9, 8, 7, 6])

In [9]:
#array of ones

In [10]:
array_of_zeros = np.zeros((3,4))
array_of_zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [11]:
array_of_zeros = np.zeros((2,3))
array_of_zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [12]:
array_of_ones = np.ones((3,4))
array_of_ones

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [13]:
array_of_ones_int = np.ones((3,4), dtype = np.int16)
array_of_ones_int

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]], dtype=int16)

In [14]:
array_of_ones_int = np.ones((5,4), dtype = np.int32)
array_of_ones_int

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [15]:
array_of_ones_int = np.ones((3,4), dtype = np.int64)
array_of_ones_int

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]], dtype=int64)

In [16]:
#Identity Matrix

In [17]:
array_eye = np.eye(4)
array_eye

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [18]:
#Req - by using Numpy func print even no upto 30

In [19]:
array_of_evens = np.arange(2,31,2)
array_of_evens

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30])