In [1]:
import numpy as np

In [2]:
#Understanding the identity matrix

In [4]:
array_eye = np.eye(4)
array_eye

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [5]:
#Does numpy except the float data types?

In [16]:
array_float = np.arange(0,2,0.3)
array_float

array([0. , 0.3, 0.6, 0.9, 1.2, 1.5, 1.8])

In [17]:
array_float.shape

(7,)

In [7]:
#creating a 2d array

In [13]:
array_2d = np.array([(2,4,6),(3,5,7)])
array_2d

array([[2, 4, 6],
       [3, 5, 7]])

In [14]:
array_2d = np.array([(4,6,2),(1,8,5)])
array_2d

array([[4, 6, 2],
       [1, 8, 5]])

In [15]:
array_2d.shape

(2, 3)

In [18]:
x = np.arange(6)
x

array([0, 1, 2, 3, 4, 5])

In [19]:
x.shape

(6,)

In [20]:
#REQ - changing the above 1d array to 2d array

In [21]:
x = np.arange(6).reshape(3,2)
x

array([[0, 1],
       [2, 3],
       [4, 5]])

In [22]:
x = np.arange(6).reshape(2,3)
x

array([[0, 1, 2],
       [3, 4, 5]])

In [23]:
x.shape

(2, 3)

In [24]:
array_nd = x.reshape(4,2)
array_nd

ValueError: cannot reshape array of size 6 into shape (4,2)

In [25]:
#1d array

In [26]:
a = np.arange(8)
a

array([0, 1, 2, 3, 4, 5, 6, 7])

In [27]:
#2d array

In [28]:
b = np.arange(12).reshape(4,3)
b

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [29]:
b.shape

(4, 3)

In [30]:
#3d array

In [31]:
c = np.arange(24).reshape(2,3,4)
c

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [32]:
c.shape

(2, 3, 4)