In [4]:
# Understanding statistical functions of Numpy

In [5]:
import numpy as np

In [7]:
test_scores = np.array([32.33,56.98,21.52,46.32,13.75,43.47])

In [8]:
print(test_scores)

[32.33 56.98 21.52 46.32 13.75 43.47]


In [9]:
type(test_scores)

numpy.ndarray

In [10]:
test_scores.shape

(6,)

In [12]:
#mean

In [13]:
print("Mean test scores of the students:")
print(np.mean(test_scores))

Mean test scores of the students:
35.72833333333333


In [14]:
#median

In [15]:
print("Median test scores of the students:")
print(np.median(test_scores))

Median test scores of the students:
37.9


In [16]:
#Working on Data sets

In [17]:
x = np.genfromtxt('salary.csv', delimiter = ',')
x

array([60000., 58000., 56967., ..., 54647., 25000., 70000.])

In [19]:
mean  = np.mean(x)
mean

55894.53879686138

In [20]:
median = np.median(x)
median

48000.0

In [21]:
sd = np.std(x)
sd

55170.37550939316

In [22]:
variance  = np.var(x)
variance

3043770333.8474483

In [24]:
mode = np.mode(x)
mode

AttributeError: module 'numpy' has no attribute 'mode'

In [25]:
# New way of using the f stings

In [27]:
print('Mean = %i' %mean)

Mean = 55894


In [28]:
print('Median = %i' %median)

Median = 48000


In [32]:
print('Satandard Deviation = %i' %sd)

Satandard Deviation = 55170


In [33]:
print('variance = %i' %variance)

variance = 3043770333


In [34]:
#Introduction to Iteration

In [35]:
a = np.arange(11)**2
a

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100], dtype=int32)

In [36]:
for i in a:
    print(i **(1/2))

0.0
1.0
2.0
3.0
4.0
5.0
6.0
7.0
8.0
9.0
10.0


In [37]:
for i in a:
    print(i **(2))

0
1
16
81
256
625
1296
2401
4096
6561
10000


In [38]:
# Iterating through multi dimentional array

In [41]:
students  = np.array([['diksha', 'neha', 'satya', 'ashok'],
                     [35,40,45,44],
                     [25,30,35,40]
                     ]
                     )

In [42]:
students

array([['diksha', 'neha', 'satya', 'ashok'],
       ['35', '40', '45', '44'],
       ['25', '30', '35', '40']], dtype='<U6')

In [52]:
split = np.split(students , 1)
split

[array([['diksha', 'neha', 'satya', 'ashok'],
        ['35', '40', '45', '44'],
        ['25', '30', '35', '40']], dtype='<U6')]

In [55]:
x = np.split(students , 3)
x

[array([['diksha', 'neha', 'satya', 'ashok']], dtype='<U6'),
 array([['35', '40', '45', '44']], dtype='<U6'),
 array([['25', '30', '35', '40']], dtype='<U6')]

In [59]:
y = np.hsplit(students , 4)
y

[array([['diksha'],
        ['35'],
        ['25']], dtype='<U6'),
 array([['neha'],
        ['40'],
        ['30']], dtype='<U6'),
 array([['satya'],
        ['45'],
        ['35']], dtype='<U6'),
 array([['ashok'],
        ['44'],
        ['40']], dtype='<U6')]